In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#with open("../DATA/Ames_Housing_Feature_Description.txt") as f:
 #   print(f.read())

In [3]:
df = pd.read_csv("../DATA/train_NO_Missing_Data.csv")

In [4]:
df.isna().sum().unique()

array([0], dtype=int64)

In [5]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [6]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [7]:
df['MSSubClass'] = df['MSSubClass'].apply(str)

In [8]:
my_object_df = df.select_dtypes(include='object') ## Selecting all string value columns

In [9]:
my_numeric_df = df.select_dtypes(exclude='object')

In [10]:
my_object_dummies = pd.get_dummies(my_object_df,drop_first=True)

In [11]:
my_object_dummies

,MSSubClass_160,MSSubClass_180,MSSubClass_190,MSSubClass_20,MSSubClass_30,MSSubClass_40,MSSubClass_45,MSSubClass_50,MSSubClass_60,MSSubClass_70,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1452,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,0
1453,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1454,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,0
1455,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1456,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [12]:
## Let's join Numeric and Object Dummies using concat function
final_df = pd.concat([my_object_dummies , my_numeric_df], axis=1)

In [13]:
final_df

,MSSubClass_160,MSSubClass_180,MSSubClass_190,MSSubClass_20,MSSubClass_30,MSSubClass_40,MSSubClass_45,MSSubClass_50,MSSubClass_60,MSSubClass_70,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,0,0,0,0,0,0,0,0,1,0,...,0,61,0,0,0,0,0,2,2008,208500
1,0,0,0,1,0,0,0,0,0,0,...,298,0,0,0,0,0,0,5,2007,181500
2,0,0,0,0,0,0,0,0,1,0,...,0,42,0,0,0,0,0,9,2008,223500
3,0,0,0,0,0,0,0,0,0,1,...,0,35,272,0,0,0,0,2,2006,140000
4,0,0,0,0,0,0,0,0,1,0,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1452,0,0,0,0,0,0,0,0,1,0,...,0,40,0,0,0,0,0,8,2007,175000
1453,0,0,0,1,0,0,0,0,0,0,...,349,0,0,0,0,0,0,2,2010,210000
1454,0,0,0,0,0,0,0,0,0,1,...,0,60,0,0,0,0,2500,5,2010,266500
1455,0,0,0,1,0,0,0,0,0,0,...,366,0,112,0,0,0,0,4,2010,142125
1456,0,0,0,1,0,0,0,0,0,0,...,736,68,0,0,0,0,0,6,2008,147500

In [14]:
final_df.corr()['SalePrice'].sort_values()

ExterQual_TA       -0.589947
KitchenQual_TA     -0.520124
FireplaceQu_None   -0.472413
BsmtQual_TA        -0.453018
GarageFinish_Unf   -0.411144
                      ...
GarageCars          0.641111
TotalBsmtSF         0.651553
GrLivArea           0.734962
OverallQual         0.795863
SalePrice           1.000000
Name: SalePrice, Length: 259, dtype: float64

In [15]:
final_df["MSSubClass_150"]=0

In [16]:
columns = final_df.columns
for col in columns:
    print (col)

MSSubClass_160
MSSubClass_180
MSSubClass_190
MSSubClass_20
MSSubClass_30
MSSubClass_40
MSSubClass_45
MSSubClass_50
MSSubClass_60
MSSubClass_70
MSSubClass_75
MSSubClass_80
MSSubClass_85
MSSubClass_90
MSZoning_FV
MSZoning_RH
MSZoning_RL
MSZoning_RM
Street_Pave
LotShape_IR2
LotShape_IR3
LotShape_Reg
LandContour_HLS
LandContour_Low
LandContour_Lvl
Utilities_NoSeWa
LotConfig_CulDSac
LotConfig_FR2
LotConfig_FR3
LotConfig_Inside
LandSlope_Mod
LandSlope_Sev
Neighborhood_Blueste
Neighborhood_BrDale
Neighborhood_BrkSide
Neighborhood_ClearCr
Neighborhood_CollgCr
Neighborhood_Crawfor
Neighborhood_Edwards
Neighborhood_Gilbert
Neighborhood_IDOTRR
Neighborhood_MeadowV
Neighborhood_Mitchel
Neighborhood_NAmes
Neighborhood_NPkVill
Neighborhood_NWAmes
Neighborhood_NoRidge
Neighborhood_NridgHt
Neighborhood_OldTown
Neighborhood_SWISU
Neighborhood_Sawyer
Neighborhood_SawyerW
Neighborhood_Somerst
Neighborhood_StoneBr
Neighborhood_Timber
Neighborhood_Veenker
Condition1_Feedr
Condition1_Norm
Condition1_PosA
Condition1_PosN
Condition1_RRAe
Condition1_RRAn
Condition1_RRNe
Condition1_RRNn
Condition2_Feedr
Condition2_Norm
Condition2_PosA
Condition2_PosN
Condition2_RRAe
Condition2_RRAn
Condition2_RRNn
BldgType_2fmCon
BldgType_Duplex
BldgType_Twnhs
BldgType_TwnhsE
HouseStyle_1.5Unf
HouseStyle_1Story
HouseStyle_2.5Fin
HouseStyle_2.5Unf
HouseStyle_2Story
HouseStyle_SFoyer
HouseStyle_SLvl
RoofStyle_Gable
RoofStyle_Gambrel
RoofStyle_Hip
RoofStyle_Mansard
RoofStyle_Shed
RoofMatl_Membran
RoofMatl_Metal
RoofMatl_Roll
RoofMatl_Tar&Grv
RoofMatl_WdShake
RoofMatl_WdShngl
Exterior1st_AsphShn
Exterior1st_BrkComm
Exterior1st_BrkFace
Exterior1st_CBlock
Exterior1st_CemntBd
Exterior1st_HdBoard
Exterior1st_ImStucc
Exterior1st_MetalSd
Exterior1st_Plywood
Exterior1st_Stone
Exterior1st_Stucco
Exterior1st_VinylSd
Exterior1st_Wd Sdng
Exterior1st_WdShing
Exterior2nd_AsphShn
Exterior2nd_Brk Cmn
Exterior2nd_BrkFace
Exterior2nd_CBlock
Exterior2nd_CmentBd
Exterior2nd_HdBoard
Exterior2nd_ImStucc
Exterior2nd_MetalSd
Exterior2nd_Other
Exterior2nd_Plywood
Exterior2nd_Stone
Exterior2nd_Stucco
Exterior2nd_VinylSd
Exterior2nd_Wd Sdng
Exterior2nd_Wd Shng
MasVnrType_BrkFace
MasVnrType_None
MasVnrType_Stone
ExterQual_Fa
ExterQual_Gd
ExterQual_TA
ExterCond_Fa
ExterCond_Gd
ExterCond_Po
ExterCond_TA
Foundation_CBlock
Foundation_PConc
Foundation_Slab
Foundation_Stone
Foundation_Wood
BsmtQual_Fa
BsmtQual_Gd
BsmtQual_None
BsmtQual_TA
BsmtCond_Gd
BsmtCond_None
BsmtCond_Po
BsmtCond_TA
BsmtExposure_Gd
BsmtExposure_Mn
BsmtExposure_No
BsmtExposure_None
BsmtFinType1_BLQ
BsmtFinType1_GLQ
BsmtFinType1_LwQ
BsmtFinType1_None
BsmtFinType1_Rec
BsmtFinType1_Unf
BsmtFinType2_BLQ
BsmtFinType2_GLQ
BsmtFinType2_LwQ
BsmtFinType2_None
BsmtFinType2_Rec
BsmtFinType2_Unf
Heating_GasA
Heating_GasW
Heating_Grav
Heating_OthW
Heating_Wall
HeatingQC_Fa
HeatingQC_Gd
HeatingQC_Po
HeatingQC_TA
CentralAir_Y
Electrical_FuseF
Electrical_FuseP
Electrical_Mix
Electrical_SBrkr
KitchenQual_Fa
KitchenQual_Gd
KitchenQual_TA
Functional_Maj2
Functional_Min1
Functional_Min2
Functional_Mod
Functional_Sev
Functional_Typ
FireplaceQu_Fa
FireplaceQu_Gd
FireplaceQu_None
FireplaceQu_Po
FireplaceQu_TA
GarageType_Attchd
GarageType_Basment
GarageType_BuiltIn
GarageType_CarPort
GarageType_Detchd
GarageType_None
GarageFinish_None
GarageFinish_RFn
GarageFinish_Unf
GarageQual_Fa
GarageQual_Gd
GarageQual_None
GarageQual_Po
GarageQual_TA
GarageCond_Fa
GarageCond_Gd
GarageCond_None
GarageCond_Po
GarageCond_TA
PavedDrive_P
PavedDrive_Y
SaleType_CWD
SaleType_Con
SaleType_ConLD
SaleType_ConLI
SaleType_ConLw
SaleType_New
SaleType_Oth
SaleType_WD
SaleCondition_AdjLand
SaleCondition_Alloca
SaleCondition_Family
SaleCondition_Normal
SaleCondition_Partial
LotFrontage
LotArea
OverallQual
OverallCond
YearBuilt
YearRemodAdd
MasVnrArea
BsmtFinSF1
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
1stFlrSF
2ndFlrSF
LowQualFinSF
GrLivArea
BsmtFullBath
BsmtHalfBath
FullBath
HalfBath
BedroomAbvGr
KitchenAbvGr
TotRmsAbvGrd
Fireplaces
GarageYrBlt
GarageCars
GarageArea
WoodDeckSF
OpenPorchSF
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
MiscVal
MoSold
YrSold
SalePrice
MSSubClass_150

In [17]:
len(columns)

260

### Arranging the columns in ascending order

In [18]:
columns_list = final_df.columns.tolist()

In [19]:
columns_list.sort()

In [20]:
final_df = final_df[columns_list]

In [21]:
final_df

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,BsmtCond_Gd,BsmtCond_None,...,SaleType_WD,ScreenPorch,Street_Pave,TotRmsAbvGrd,TotalBsmtSF,Utilities_NoSeWa,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856,854,0,3,0,0,0,0,0,0,...,1,0,1,8,856,0,0,2003,2003,2008
1,1262,0,0,3,0,0,0,0,0,0,...,1,0,1,6,1262,0,298,1976,1976,2007
2,920,866,0,3,0,0,0,0,0,0,...,1,0,1,6,920,0,0,2001,2002,2008
3,961,756,0,3,0,0,0,0,1,0,...,1,0,1,7,756,0,0,1915,1970,2006
4,1145,1053,0,4,0,0,0,0,0,0,...,1,0,1,9,1145,0,192,2000,2000,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1452,953,694,0,3,0,0,0,0,0,0,...,1,0,1,7,953,0,0,1999,2000,2007
1453,2073,0,0,3,0,0,0,0,0,0,...,1,0,1,7,1542,0,349,1978,1988,2010
1454,1188,1152,0,4,0,0,0,0,1,0,...,1,0,1,9,1152,0,0,1941,2006,2010
1455,1078,0,0,2,0,0,0,0,0,0,...,1,0,1,5,1078,0,366,1950,1996,2010
1456,1256,0,0,3,0,0,0,0,0,0,...,1,0,1,6,1256,0,736,1965,1965,2008

In [22]:
final_df.to_csv("../DATA/final_df.csv", index=False)